language: java
jdk: oraclejdk8
script: mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
deploy:
  - provider: releases
    api_key:
      secure: $GH_KEY
    file: $GH_RELEASE_FILE
    skip_cleanup: true
    draft: true
    on:
      repo: TheNLGamerZone/QuestPlugin
      tags: true

